### ISSUE TITLE
[Closed] It doesn't seem to display anything on my forum?

### ISSUE THREAD

**Issue by groovybluedog** [JN-Jones/Announcement#6]
Relatively new forum, running only MyBB GoMobile. I've installed the plugin, added a correctly configured announcement, but nothing is showing up.

**Comment by JN-Jones** [comment]
Hi, sorry for the late reply.

Depending on where the announcement should be displayed, there are a few templates to check:
* The `index` template should have a variable `$announcement` somewhere near `$header`
* Same goes for the templates `forumdisplay` and `showthread` (note that the variable is named `fdannouncement` in the `forumdisplay` template)
* The `header` template should have the `$announcement` variable somewhere near `$pm_notice`

If those variables are missing readd them and test it again.

**Comment by groovybluedog** [comment]
Thanks for the help but thankfully I've just got around to sorting this out but it worked first time on installation this time! Odd it didn't work first time, but I'm sure your solution may help someone else out... odd to say the least. I do have an idea which I'll put in a different issue.
